remove usage page check
OpenAnnePro/AnnePro2-Tools pull request #12
Opened 2021-02-04 11:14 UTC by jmarmstrong1207

There is an issue with a user having a usage page of 0 rather than 1, causing errors for him. Not sure why, but removed these for a quick fix

2021-02-05 05:01 UTC, Codetector1374 commented
I understand the problem we have here, however, let's implement a temporary fix that we use the "highest interface found" for that device. Because on the C15 I have, it show up as three interface in recovery mode. And this will likely select the wrong interface for C15s.

2021-02-07 02:23 UTC, jmarmstrong1207 commented
I added what was checked before for c15 Is this fine?

2021-02-14 18:34 UTC, danil-tolkachev commented
Won't work on my c18 without this PR.

2021-02-15 04:52 UTC, Codetector1374 requested changes

2021-02-15 04:52 UTC, Codetector1374 commented on src/annepro2.rs
> +                    ((dev.usage() == USAGE_C15 && dev.product_id() == PID_C15 && dev.interface_number() == 1) ||
If we are not checking `usage_page` then we should remove the check for `usage` as well.

2021-02-15 14:11 UTC, Codetector1374 approved these changes
LGTM

2021-02-15 14:11 UTC, merged